parameters:
  jenkins:
    client:
      job:
        galera_verify_restore:
          type: workflow-scm
          name: galera-verify-restore
          display_name: "Verify and Restore Galera cluster"
          discard:
            build:
              keep_num: 50
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: ${_param:jenkins_gerrit_credentials}
            script: galera-cluster-verify-restore.groovy
          param:
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
            ASK_CONFIRMATION:
              type: boolean
              default: 'true'
            CHECK_TIME_SYNC:
              type: boolean
              default: 'true'
            VERIFICATION_RETRIES:
              type: string
              default: 5
            RESTORE_TYPE:
              type: choice
              choices:
                - 'BACKUP_AND_RESTORE'
                - 'ONLY_RESTORE'
                - 'RESTART_CLUSTER'
              description: "Choose required behavior. See documentation for more information."
