#
# Jobs to run given states on given Salt master environment's
#
parameters:
  jenkins:
    client:
      job:
        update-glusterfs-servers:
          type: workflow-scm
          description: Update glusterfs-server package on corresponding hosts
          concurrent: true
          discard:
            build:
              keep_num: 10
            artifact:
              keep_num: 10
          display_name: "Update glusterfs servers"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: ${_param:jenkins_gerrit_credentials}
            script: update-glusterfs-servers.groovy
          param:
            DRIVE_TRAIN_PARAMS:
              type: text
              description: "Yaml based DriveTrain releated params"
              default: |
                ---
                SALT_MASTER_URL: "${_param:jenkins_salt_api_url}"
                SALT_MASTER_CREDENTIALS: "salt"
                # Salt compound target to match nodes to be updated [*, G@osfamily:debian].
                TARGET_SERVERS: "I@glusterfs:server"
                # Does not validate server availability/status before update
                IGNORE_SERVER_STATUS: false
                # Update GlusterFS even there is a non-replicated volume
                IGNORE_NON_REPLICATED_VOLUMES: false
