#
# Jobs to upgrade Galera packages on given Salt master environment
#
parameters:
  jenkins:
    client:
      job:
        deploy-upgrade-galera:
          type: workflow-scm
          concurrent: true
          discard:
            build:
              keep_num: 10
            artifact:
              keep_num: 10
          display_name: "Deploy - upgrade Galera cluster"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: ${_param:jenkins_gerrit_credentials}
            script: openstack-galera-upgrade.groovy
          param:
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SHUTDOWN_CLUSTER:
              type: boolean
              default: 'false'
              description: "Shutdown all mysql instances on target nodes during upgrade"
            OS_DIST_UPGRADE:
              type: boolean
              default: 'false'
              description: "Upgrade system packages including kernel (apt-get dist-upgrade)"
            OS_UPGRADE:
              type: boolean
              default: 'false'
              description: "Upgrade all installed applications (apt-get upgrade)"
            INTERACTIVE:
              type: boolean
              default: 'true'
              description: "Ask interactive questions during pipeline run (bool)"
            TARGET_SERVERS:
              type: string
              default: 'dbs*'
              description: "Salt compound expression to get mysql servers to upgrade."
