classes:
- system.openssh.client.root
parameters:
  openssh:
    client:
      enabled: true
      user:
        root:
          enabled: true
          user: ${linux:system:user:root}
          private_key:
            key: ${_param:root_private_key}
            type: rsa

