classes:
- system.ceph.backup.client.single
- cluster.openstack-sh.infra.backup.allow_root_ssh
parameters:
  _param:
    ceph_remote_backup_server: ${_param:infra_kvm_node03_address}
  ceph:
    backup:
      client:
        target:
          backup_dir: /srv/volumes/backup/ceph
