classes:
- system.linux.system.sudo
- system.openssh.server.team.members.deprecated.ahecko
- system.openssh.server.team.members.deprecated.pmichalec
parameters:
  _param:
    linux_system_user_sudo: true
