classes:
- cluster.openstack-sh.kubernetes.common
- cluster.openstack-sh.kubernetes.networking.physical
- cluster.openstack-sh.infra
parameters:
  _param:
    deploy_nic: eth0
    primary_first_nic: eth1
    primary_second_nic: eth2
