parameters:
  prometheus:
    elasticsearch_exporter:
      queries:
        compute_instance:
          # Produces metrics:
          #   - compute_instance_event_doc_count{event="example"}
          #   - compute_instance_event_sum_other_doc_count
          #   - compute_instance_event_doc_count_error_upper_bound
          #
          indices: '<notification-{now/d}>'
          interval: 600
          json: |
            {
              "size": 0,
              "aggs": {
                "event": {
                  "terms": {
                    "field": "event_type.keyword"
                  }
                }
              }
            }

        compute_instance_create_start:
          # Produces metrics:
          #   - compute_instance_create_start_event_doc_count
          #   - compute_instance_create_start_event_sum_other_doc_count
          #   - compute_instance_create_start_event_doc_count_error_upper_bound
          #   - compute_instance_create_start_hits
          #   - compute_instance_create_start_took_milliseconds
          #
          indices: '<notification-{now/d}>'
          interval: 60
          json: |
            {
              "size": 0,
              "aggs": {
                "event": {
                  "filter": {
                    "term": {
                      "event_type.keyword": "compute.instance.create.start"
                    }
                  }
                }
              }
            }

        compute_instance_create_end:
          # Produces metrics:
          #   - compute_instance_create_end_event_doc_count
          #   - compute_instance_create_end_event_sum_other_doc_count
          #   - compute_instance_create_end_event_doc_count_error_upper_bound
          #   - compute_instance_create_end_hits
          #   - compute_instance_create_end_took_milliseconds
          #
          indices: '<notification-{now/d}>'
          interval: 60
          json: |
            {
              "size": 0,
              "aggs": {
                "event": {
                  "filter": {
                    "term": {
                      "event_type.keyword": "compute.instance.create.end"
                    }
                  }
                }
              }
            }

        compute_instance_create_error:
          # Produces metrics:
          #   - compute_instance_create_error_event_doc_count
          #   - compute_instance_create_error_event_sum_other_doc_count
          #   - compute_instance_create_error_event_doc_count_error_upper_bound
          #   - compute_instance_create_error_hits
          #   - compute_instance_create_error_took_milliseconds
          #
          indices: '<notification-{now/d}>'
          interval: 60
          json: |
            {
              "size": 0,
              "aggs": {
                "event": {
                  "filter": {
                    "term": {
                      "event_type.keyword": "compute.instance.create.error"
                    }
                  }
                }
              }
            }
