parameters:
  nginx:
    server:
      enabled: true
      site:
        nginx_proxy_prometheus_server_lts:
          enabled: true
          type: nginx_proxy
          name: prometheus_server_lts
          proxy:
            host: ${_param:stacklight_telemetry_address}
            port: 9090
            protocol: http
          host:
            name: ${_param:cluster_public_host}
            port: 9090
            protocol: https
          ssl: ${_param:nginx_proxy_ssl}
